
CREATE TABLE [dbo].[PRODUTOS](
	[CÓDIGO] VARCHAR(10) NOT NULL,
	[DESCRITOR] VARCHAR(100) NULL,
	[SABOR] VARCHAR(50) NULL,
	[TAMANHO] VARCHAR(50) NULL,
	[EMBALAGEM] VARCHAR(50) NULL,
	[PREÇO LISTA] FLOAT NULL,
 CONSTRAINT [PK_PRODUTOS] PRIMARY KEY CLUSTERED ([CÓDIGO])
) 

CREATE TABLE [dbo].[CLIENTES](
	[CPF] VARCHAR(11) NOT NULL,
	[NOME] VARCHAR(50) NULL,
	[ENDEREÇO] VARCHAR(100) NULL,
	[BAIRRO] VARCHAR(50) NULL,
	[CIDADE] VARCHAR(50) NULL,
	[ESTADO] VARCHAR(50) NULL,
	[CEP] VARCHAR(8) NULL,
	[DATA NASCIMENTO] DATE NULL,
	[IDADE] INT NULL,
	[SEXO] VARCHAR(1),
	[LIMITE DE CRÉDITO] FLOAT,
	[VOLUME DE COMPRA] FLOAT,
	[PRIMEIRA COMPRA] BIT,
 CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED ([CPF])
) 

CREATE TABLE [dbo].[VENDEDORES](
	[MATRÍCULA] VARCHAR(5) NOT NULL,
	[NOME] VARCHAR(100) NULL,
	[BAIRRO] VARCHAR(50) NULL,
	[COMISSÃO] FLOAT NULL,
	[DATA ADMISSÃO] DATE NULL,
	[FÉRIAS] BIT,
 CONSTRAINT [PK_VENDDORES] PRIMARY KEY CLUSTERED ([MATRÍCULA])
) 

CREATE TABLE [dbo].[NOTAS](
	[NÚMERO] VARCHAR(5) NOT NULL,
	[DATA] DATE NULL,
	[CPF] VARCHAR(11) NULL,
	[MATRICULA] VARCHAR(5) NULL,
	[IMPOSTO] FLOAT NULL,
 CONSTRAINT [PK_NOTAS] PRIMARY KEY CLUSTERED ([NÚMERO])
) 

CREATE TABLE [dbo].[ITENS VENDIDOS](
	[NÚMERO] VARCHAR(5) NOT NULL,
	[CÓDIGO] VARCHAR(10) NOT NULL,
	[QUANTIDADE] INT NULL,
	[PREÇO] FLOAT NULL,
 CONSTRAINT [PK_ITENS_VENDIDOS] PRIMARY KEY CLUSTERED ([NÚMERO], [CÓDIGO])
) 




