-- VARIAVEIS DO CURSOR
DECLARE @CODIGO VARCHAR(10), 
        @NOME VARCHAR(50);

--CRIANDO CURSOS
DECLARE CUR_NOME CURSOR
FOR SELECT [CODIGO DO PRODUTO], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS] ORDER BY [NOME DO PRODUTO];

--ABRINDO CURSOR
OPEN CUR_NOME;

-- SELECIONA OS DADOS
FETCH NEXT FROM CUR_NOME
 INTO @CODIGO, @NOME;

WHILE @@FETCH_STATUS = 0
BEGIN
	FETCH NEXT FROM CUR_NOME
    INTO @CODIGO, @NOME;

END

SELECT @CODIGO, @NOME;

--FECHA CURSOR
CLOSE CUR_NOME;
DEALLOCATE CUR_NOME;