

IF OBJECT_ID('TABELA_TESTE','U') IS NOT NULL
BEGIN
	DROP TABLE TABELA_TESTE
END
CREATE TABLE TABELA_TESTE (
	ID VARCHAR(10)
)

SELECT GETDATE()
SELECT DATENAME(WEEKDAY,GETDATE())
SELECT DATENAME(WEEKDAY,DATEADD(DAY,6,GETDATE()))

DECLARE @DIA_SEMANA VARCHAR(20)
DECLARE @NUMERO_DIAS INT
SET @NUMERO_DIAS = 4
SET @DIA_SEMANA = DATENAME(WEEKDAY,DATEADD(DAY, @NUMERO_DIAS, GETDATE()))
PRINT @DIA_SEMANA
IF @DIA_SEMANA = 'DOMINGO' OR @DIA_SEMANA = 'SABADO'
	PRINT 'ESTE DIA É FINAL DE SEMANA'
ELSE
	PRINT 'ESTE DIA É DIA DE SEMANA'



DECLARE @DATANOTA DATE
DECLARE @NUMNOTAS INT
SET @DATANOTA = '20170102'
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
    WHERE DATA = @DATANOTA
IF @NUMNOTAS > 70
    PRINT 'Muita nota'
ELSE
    PRINT 'Pouca nota'
PRINT @NUMNOTAS


SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES]
where BAIRRO = 'Jardins'

DECLARE @LIMITE_MAXIMO FLOAT, @LIMITE_ATUAL FLOAT
DECLARE @BAIRRO VARCHAR(20)

SET @BAIRRO = 'Jardins'
SET @LIMITE_MAXIMO = '500000'

SELECT @LIMITE_ATUAL = SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO
IF @LIMITE_MAXIMO <= (SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO)
BEGIN
	PRINT 'VALOR ESTOURADO LIMITE PASSOU'
END
ELSE 
BEGIN
	PRINT 'VALOR NÃO ESTOUROU'
END










