
DECLARE @IDADE INT
DECLARE @NOME VARCHAR(200)
DECLARE @DATA DATE

DECLARE @NOME2 VARCHAR(200), @DATA2 DATE, @IDADE2 INT 

SET @IDADE = '20'
PRINT @IDADE

SET @NOME = 'ANDERSON OLIVEIRA DA SILVA'
PRINT @NOME

SET @DATA = '2023-05-01'
PRINT @DATA

DECLARE @CPF VARCHAR(12)
SET @CPF = '1471156710'

SELECT NOME,[DATA DE NASCIMENTO], IDADE FROM [TABELA DE CLIENTES] 
WHERE CPF = @CPF

SELECT @NOME = NOME, @DATA2 = [DATA DE NASCIMENTO], @IDADE2 = IDADE 
FROM [TABELA DE CLIENTES]
WHERE CPF = @CPF

SELECT * FROM [TABELA DE VENDEDORES]

DECLARE @MATRICULA VARCHAR(5), @NOME3 VARCHAR(100), @PERCENTUAL FLOAT, @DATA3 DATE, @FERIAS BIT, @BAIRRO VARCHAR(100)

SET @MATRICULA = '01234'
SET @NOME3 = 'ANDERSON OLIVEIRA'
SET @PERCENTUAL = '0.20'
SET @DATA3 = '2023-05-01'
SET @FERIAS = '1'
SET @BAIRRO = 'BATEL'

INSERT INTO [TABELA DE VENDEDORES]
VALUES(@MATRICULA,@NOME3,@PERCENTUAL,@DATA3,@FERIAS,@BAIRRO)

DECLARE @NUMNOTAS INT
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS]
WHERE DATA = '2017-01-01'
PRINT @NUMNOTAS

DECLARE @DATANOTA DATE
DECLARE @NUMNOTAS INT
SET @DATANOTA = '20170102'
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
    WHERE DATA = @DATANOTA
IF @NUMNOTAS > 70
    PRINT 'Muita nota'
ELSE
    PRINT 'Pouca nota'
PRINT @NUMNOTAS















